Repository AutoeverInsideMovie/Insidemovie-BE, pull requests merged in 2025-07, with the labels that each got.

#2 [FEAT] 프로젝트 공통 코드 추가, Swagger 설정
  build.gradle
  src/main/java/com/insidemovie/backend/api/sample/controller/SampleController.java
  src/main/java/com/insidemovie/backend/api/sample/dto/.gitkeep
  src/main/java/com/insidemovie/backend/api/sample/entity/.gitkeep
  src/main/java/com/insidemovie/backend/api/sample/repository/.gitkeep
  src/main/java/com/insidemovie/backend/api/sample/service/.gitkeep
  src/main/java/com/insidemovie/backend/api/sample2/.gitkeep
  src/main/java/com/insidemovie/backend/common/advice/ControllerExceptionAdvice.java
  src/main/java/com/insidemovie/backend/common/config/.gitkeep
  src/main/java/com/insidemovie/backend/common/config/swagger/SwaggerConfig.java
  src/main/java/com/insidemovie/backend/common/entity/BaseTimeEntity.java
  src/main/java/com/insidemovie/backend/common/exception/BadRequestException.java
  src/main/java/com/insidemovie/backend/common/exception/BaseException.java
  src/main/java/com/insidemovie/backend/common/exception/InternalServerException.java
  src/main/java/com/insidemovie/backend/common/exception/NotFoundException.java
  src/main/java/com/insidemovie/backend/common/exception/UnAuthorizedException.java
  src/main/java/com/insidemovie/backend/common/response/ApiResponse.java
  src/main/java/com/insidemovie/backend/common/response/ErrorStatus.java
  src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
Labels: FEAT

#4 [FEAT] 엔티티 또연습..
  src/main/java/com/insidemovie/backend/api/sample/entity/User.java
Labels: FEAT

#6 [FEAT] CI 설정
  .github/workflows/change-pr-base.yml
Labels: FEAT

#15 [FEAT] 회원가입 및 로그인 기능 구현
  build.gradle
  src/main/java/com/insidemovie/backend/api/constant/Authority.java
  src/main/java/com/insidemovie/backend/api/jwt/JwtFilter.java
  src/main/java/com/insidemovie/backend/api/jwt/JwtProvider.java
  src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java
  src/main/java/com/insidemovie/backend/api/member/dto/MemberLoginRequestDto.java
  src/main/java/com/insidemovie/backend/api/member/dto/MemberLoginResponseDto.java
  src/main/java/com/insidemovie/backend/api/member/dto/MemberSignupRequestDto.java
  src/main/java/com/insidemovie/backend/api/member/dto/TokenRequestDto.java
  src/main/java/com/insidemovie/backend/api/member/dto/TokenResponseDto.java
  src/main/java/com/insidemovie/backend/api/member/entity/Member.java
  src/main/java/com/insidemovie/backend/api/member/repository/MemberRepository.java
  src/main/java/com/insidemovie/backend/api/member/service/MemberService.java
  src/main/java/com/insidemovie/backend/api/sample/controller/SampleController.java
  src/main/java/com/insidemovie/backend/api/sample/dto/.gitkeep
  src/main/java/com/insidemovie/backend/api/sample/entity/.gitkeep
  src/main/java/com/insidemovie/backend/api/sample/entity/User.java
  src/main/java/com/insidemovie/backend/api/sample/repository/.gitkeep
  src/main/java/com/insidemovie/backend/api/sample/service/.gitkeep
  src/main/java/com/insidemovie/backend/api/sample2/.gitkeep
  src/main/java/com/insidemovie/backend/common/config/security/SecurityConfig.java
  src/main/java/com/insidemovie/backend/common/response/ErrorStatus.java
  src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
Labels: FEAT

#19 [FEAT] Swagger Authorize 설정
  src/main/java/com/insidemovie/backend/common/config/.gitkeep
  src/main/java/com/insidemovie/backend/common/config/swagger/SwaggerConfig.java
Labels: FEAT

#23 [FEAT] Member 엔티티에 관리자 추가
  src/main/java/com/insidemovie/backend/BackendApplication.java
  src/main/java/com/insidemovie/backend/api/admin/controller/AdminController.java
  src/main/java/com/insidemovie/backend/api/jwt/JwtProvider.java
  src/main/java/com/insidemovie/backend/api/member/entity/Member.java
  src/main/java/com/insidemovie/backend/api/member/service/MemberService.java
  src/main/java/com/insidemovie/backend/common/config/security/SecurityConfig.java
Labels: FEAT

#43 [FEAT] 스케줄링으로 영화 목록 db에 저장
  build.gradle
  src/main/java/com/insidemovie/backend/BackendApplication.java
  src/main/java/com/insidemovie/backend/api/movie/config/RedisConfig.java
  src/main/java/com/insidemovie/backend/api/movie/config/RestTemplateConfig.java
  src/main/java/com/insidemovie/backend/api/movie/dto/PaginatedResponse.java
  src/main/java/com/insidemovie/backend/api/movie/dto/TmdbMovieDto.java
  src/main/java/com/insidemovie/backend/api/movie/dto/TmdbResponse.java
  src/main/java/com/insidemovie/backend/api/movie/entity/Movie.java
  src/main/java/com/insidemovie/backend/api/movie/repository/MovieRepository.java
  src/main/java/com/insidemovie/backend/api/movie/scheduler/MovieDataScheduler.java
  src/main/java/com/insidemovie/backend/api/movie/service/MoviesService.java
  src/main/java/com/insidemovie/backend/common/config/security/SecurityConfig.java
Labels: FEAT

#45 [FEAT] 관리자 회원 관리 기능 구현
  src/main/java/com/insidemovie/backend/api/admin/controller/AdminController.java
  src/main/java/com/insidemovie/backend/api/admin/dto/AdminMemberDTO.java
  src/main/java/com/insidemovie/backend/api/admin/service/AdminMemberService.java
  src/main/java/com/insidemovie/backend/api/jwt/JwtProvider.java
  src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java
  src/main/java/com/insidemovie/backend/api/member/entity/Member.java
  src/main/java/com/insidemovie/backend/api/member/repository/MemberRepository.java
  src/main/java/com/insidemovie/backend/api/review/controller/ReviewController.java
  src/main/java/com/insidemovie/backend/api/review/repository/ReviewRepository.java
  src/main/java/com/insidemovie/backend/common/config/security/SecurityConfig.java
  src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
Labels: FEAT

#67 [FIX] @Builder 필드 초기값 누락 경고 해결
  src/main/java/com/insidemovie/backend/api/jwt/JwtFilter.java
  src/main/java/com/insidemovie/backend/api/member/entity/Member.java
  src/main/java/com/insidemovie/backend/api/report/entity/Report.java
  src/main/java/com/insidemovie/backend/api/review/entity/Review.java
  src/main/resources/application.yml
Labels: FIX

#68 Feat/#64 MySQL 데이터베이스 자동 연결 기능 추가
  src/main/java/com/insidemovie/backend/BackendApplication.java
  src/main/java/com/insidemovie/backend/api/movie/scheduler/MovieDataScheduler.java
  src/main/java/com/insidemovie/backend/api/movie/scheduler/MovieSeedScheduler.java
  src/main/java/com/insidemovie/backend/common/config/db/DatabaseInitializer.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: FEAT

#87 [FEAT] 내가 작성한 리뷰들의 감정 평균, 대표감정 조회 기능 구현
  src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java
  src/main/java/com/insidemovie/backend/api/member/dto/EmotionAvgDTO.java
  src/main/java/com/insidemovie/backend/api/member/entity/MemberEmotionSummary.java
  src/main/java/com/insidemovie/backend/api/member/repository/MemberEmotionSummaryRepository.java
  src/main/java/com/insidemovie/backend/api/member/service/MemberService.java
  src/main/java/com/insidemovie/backend/api/review/repository/EmotionRepository.java
  src/main/java/com/insidemovie/backend/api/review/repository/EmotionRespository.java
  src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
  src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
Labels: FEAT

#88 Feat/#79 박스오피스 데이터 TMDB에 연결
  src/main/java/com/insidemovie/backend/api/movie/dto/boxoffice/DailyBoxOfficeResponseDTO.java
  src/main/java/com/insidemovie/backend/api/movie/dto/boxoffice/WeeklyBoxOfficeResponseDTO.java
  src/main/java/com/insidemovie/backend/api/movie/dto/tmdb/MovieDetailDTO.java
  src/main/java/com/insidemovie/backend/api/movie/dto/tmdb/SearchMovieResponseDTO.java
  src/main/java/com/insidemovie/backend/api/movie/dto/tmdb/SearchMovieWrapperDTO.java
  src/main/java/com/insidemovie/backend/api/movie/entity/Movie.java
  src/main/java/com/insidemovie/backend/api/movie/entity/boxoffice/DailyBoxOfficeEntity.java
  src/main/java/com/insidemovie/backend/api/movie/entity/boxoffice/WeeklyBoxOfficeEntity.java
  src/main/java/com/insidemovie/backend/api/movie/repository/DailyBoxOfficeRepository.java
  src/main/java/com/insidemovie/backend/api/movie/repository/WeeklyBoxOfficeRepository.java
  src/main/java/com/insidemovie/backend/api/movie/scheduler/MovieUpdateScheduler.java
  src/main/java/com/insidemovie/backend/api/movie/service/BoxOfficeService.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java
  src/main/java/com/insidemovie/backend/api/movie/service/MoviesService.java
  src/main/resources/application.yml
Labels: FEAT

#85 [FEAT] 좋아요 한 영화 목록 조회
  src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java
  src/main/java/com/insidemovie/backend/api/movie/dto/MyMovieResponseDTO.java
  src/main/java/com/insidemovie/backend/api/movie/repository/MovieLikeRepository.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieLikeService.java
  src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
  src/main/resources/application.yml
Labels: FEAT

#95 [FIX] 카카오 회원가입, 로그인 로직 분리
  src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java
  src/main/java/com/insidemovie/backend/api/member/service/MemberService.java
  src/main/java/com/insidemovie/backend/common/config/security/SecurityConfig.java
  src/main/java/com/insidemovie/backend/common/response/ErrorStatus.java
  src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
Labels: FIX

#97 [FIX] 코드 오타 및 오류 수정
  src/main/java/com/insidemovie/backend/api/movie/controller/MovieController.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java
  src/main/java/com/insidemovie/backend/common/config/security/SecurityConfig.java
Labels: FIX

#101 [FEAT] 이메일 회원가입, 카카오 회원가입 반환값 추가
  src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java
  src/main/java/com/insidemovie/backend/api/member/service/MemberService.java
Labels: FEAT

#103 [FEAT] 프로필 이미지 변경 기능 구현
  src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java
  src/main/java/com/insidemovie/backend/api/member/dto/ProfileEmotionUpdateRequestDto.java
  src/main/java/com/insidemovie/backend/api/member/entity/Member.java
  src/main/java/com/insidemovie/backend/api/member/service/MemberService.java
  src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
Labels: FEAT

#108 [REFAC] 리뷰 API 구조 변경
  src/main/java/com/insidemovie/backend/api/movie/controller/MovieController.java
  src/main/java/com/insidemovie/backend/api/review/controller/ReviewController.java
  src/main/java/com/insidemovie/backend/api/review/dto/ReviewCreateDTO.java
  src/main/java/com/insidemovie/backend/api/review/dto/ReviewUpdateDTO.java
  src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
  src/main/java/com/insidemovie/backend/common/config/security/SecurityConfig.java
Labels: REFAC

#109 [FEAT]영화 타이틀로 검색 기능
  src/main/java/com/insidemovie/backend/api/constant/GenreType.java
  src/main/java/com/insidemovie/backend/api/movie/controller/MovieController.java
  src/main/java/com/insidemovie/backend/api/movie/dto/MovieSearchReqDto.java
  src/main/java/com/insidemovie/backend/api/movie/dto/MovieSearchResDto.java
  src/main/java/com/insidemovie/backend/api/movie/dto/PageResDto.java
  src/main/java/com/insidemovie/backend/api/movie/dto/tmdb/SearchMovieResponseDTO.java
  src/main/java/com/insidemovie/backend/api/movie/entity/Movie.java
  src/main/java/com/insidemovie/backend/api/movie/entity/MovieGenre.java
  src/main/java/com/insidemovie/backend/api/movie/repository/GenreRepository.java
  src/main/java/com/insidemovie/backend/api/movie/repository/MovieGenreRepository.java
  src/main/java/com/insidemovie/backend/api/movie/repository/MovieRepository.java
  src/main/java/com/insidemovie/backend/api/movie/scheduler/MovieUpdateScheduler.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieDetailService.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java
  src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
  src/main/resources/application.yml
Labels: FEAT

#112 [FIX] 오류 수정
  src/main/java/com/insidemovie/backend/api/movie/service/MovieDetailService.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java
Labels: FIX

#115 [FEAT] 닉네임 중복 확인 기능 추가
  src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java
  src/main/java/com/insidemovie/backend/api/member/dto/NicknameCheckResponseDTO.java
  src/main/java/com/insidemovie/backend/api/member/service/MemberService.java
  src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
Labels: FEAT

#116 [FEAT] 인기 영화 조회 기능 추가
  src/main/java/com/insidemovie/backend/api/movie/controller/MovieController.java
  src/main/java/com/insidemovie/backend/api/movie/repository/MovieRepository.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java
  src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
Labels: FEAT

#119 [REFAC] 영화 상세보기 응답 변경
  src/main/java/com/insidemovie/backend/BackendApplication.java
  src/main/java/com/insidemovie/backend/api/movie/controller/MovieController.java
  src/main/java/com/insidemovie/backend/api/movie/dto/GenreResponse.java
  src/main/java/com/insidemovie/backend/api/movie/dto/MovieDetailResDto.java
  src/main/java/com/insidemovie/backend/api/movie/dto/TmdbGenreResponseDto.java
  src/main/java/com/insidemovie/backend/api/movie/dto/tmdb/MovieDetailDTO.java
  src/main/java/com/insidemovie/backend/api/movie/entity/Genre.java
  src/main/java/com/insidemovie/backend/api/movie/repository/GenreRepository.java
  src/main/java/com/insidemovie/backend/api/movie/repository/MovieGenreRepository.java
  src/main/java/com/insidemovie/backend/api/movie/service/BoxOfficeService.java
  src/main/java/com/insidemovie/backend/api/movie/service/GenreInitService.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieDetailService.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java
  src/main/java/com/insidemovie/backend/api/movie/service/MoviesService.java
  src/main/java/com/insidemovie/backend/api/movie/service/TmdbClient.java
Labels: REFAC

#122 [FIX] 닉네임 수정 SecurityConfig 엔드포인트 추가
  src/main/java/com/insidemovie/backend/common/config/security/SecurityConfig.java
Labels: FIX

#126 [REFAC] TMDB ID를 Movie ID로 변경하여 응답 데이터 구조 수정
  src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java
Labels: REFAC

#128 [FEAT] 사용자 정보 조회 시 사용자 감정 상태, 좋아요 개수 등 반환 값 추가
  src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java
  src/main/java/com/insidemovie/backend/api/member/dto/MemberInfoDto.java
  src/main/java/com/insidemovie/backend/api/member/service/MemberService.java
  src/main/java/com/insidemovie/backend/api/movie/repository/MovieLikeRepository.java
  src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
Labels: FEAT

#129 [FIX] 관리자 대시보드에 누적 통계 (일별/월별) 추가 구현
  src/main/java/com/insidemovie/backend/api/admin/dto/AdminDashboardDTO.java
  src/main/java/com/insidemovie/backend/api/admin/service/AdminService.java
  src/main/java/com/insidemovie/backend/api/member/repository/MemberRepository.java
  src/main/java/com/insidemovie/backend/api/report/repository/ReportRepository.java
  src/main/java/com/insidemovie/backend/api/review/repository/ReviewRepository.java
Labels: FIX

#130 [FEAT]영화 장르별 추천
  src/main/java/com/insidemovie/backend/api/constant/GenreType.java
  src/main/java/com/insidemovie/backend/api/movie/controller/MovieController.java
  src/main/java/com/insidemovie/backend/api/movie/dto/PageResDto.java
  src/main/java/com/insidemovie/backend/api/movie/dto/RecommendedMovieReqDto.java
  src/main/java/com/insidemovie/backend/api/movie/dto/RecommendedMovieResDto.java
  src/main/java/com/insidemovie/backend/api/movie/entity/MovieGenre.java
  src/main/java/com/insidemovie/backend/api/movie/repository/MovieGenreRepository.java
  src/main/java/com/insidemovie/backend/api/movie/repository/MovieLikeRepository.java
  src/main/java/com/insidemovie/backend/api/movie/repository/MovieRepository.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java
  src/main/java/com/insidemovie/backend/common/response/ErrorStatus.java
  src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
Labels: FEAT

#135 [FIX] 박스오피스 스케줄러 관련 서비스 로직 수정 및 박스오피스 영화의 상세보기 API 기능 추가
  src/main/java/com/insidemovie/backend/api/movie/controller/BoxOfficeController.java
  src/main/java/com/insidemovie/backend/api/movie/dto/boxoffice/BoxOfficeListDTO.java
  src/main/java/com/insidemovie/backend/api/movie/dto/boxoffice/DailyBoxOfficeResponseDTO.java
  src/main/java/com/insidemovie/backend/api/movie/dto/boxoffice/WeeklyBoxOfficeResponseDTO.java
  src/main/java/com/insidemovie/backend/api/movie/entity/boxoffice/DailyBoxOfficeEntity.java
  src/main/java/com/insidemovie/backend/api/movie/entity/boxoffice/WeeklyBoxOfficeEntity.java
  src/main/java/com/insidemovie/backend/api/movie/repository/DailyBoxOfficeRepository.java
  src/main/java/com/insidemovie/backend/api/movie/repository/MovieGenreRepository.java
  src/main/java/com/insidemovie/backend/api/movie/repository/WeeklyBoxOfficeRepository.java
  src/main/java/com/insidemovie/backend/api/movie/scheduler/DailyBoxOfficeScheduler.java
  src/main/java/com/insidemovie/backend/api/movie/scheduler/WeeklyBoxOfficeScheduler.java
  src/main/java/com/insidemovie/backend/api/movie/service/BoxOfficeService.java
  src/main/java/com/insidemovie/backend/common/config/security/SecurityConfig.java
  src/main/java/com/insidemovie/backend/common/response/ErrorStatus.java
  src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
  src/main/resources/application.yml
Labels: FEAT, FIX

#139 [FEAT] 마이페이지에서 내가 좋아요 한 영화 목록 응답 데이터 추가
  src/main/java/com/insidemovie/backend/api/constant/EmotionType.java
  src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java
  src/main/java/com/insidemovie/backend/api/movie/dto/MyMovieResponseDTO.java
  src/main/java/com/insidemovie/backend/api/movie/dto/PageResDto.java
  src/main/java/com/insidemovie/backend/api/movie/repository/MovieEmotionSummaryRepository.java
  src/main/java/com/insidemovie/backend/api/movie/repository/MovieLikeRepository.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieLikeService.java
  src/main/java/com/insidemovie/backend/common/response/ErrorStatus.java
Labels: FEAT

#142 [REFAC] 페이지네이션 응답 구조 PageResult로 변경
  src/main/java/com/insidemovie/backend/api/admin/controller/AdminController.java
  src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java
  src/main/java/com/insidemovie/backend/api/review/controller/ReviewController.java
  src/main/java/com/insidemovie/backend/common/response/PageResult.java
Labels: FEAT, REFAC

#146 [FIX] 영화 감정 상태 리뷰가 하나도 없을 때 대표 감정이 JOY로 나오는 거 NEUTRAL로 수정
  src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java
  src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
Labels: FIX

#151 [FEAT] 마이페이지에서 내가 작성한 리뷰 목록 응답 데이터 추가
  src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java
  src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
Labels: FEAT

#153 [FEAT] 내가 본 영화 리스트 조회 기능
  src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java
  src/main/java/com/insidemovie/backend/api/movie/dto/MovieSearchResDto.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieLikeService.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java
  src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
Labels: FEAT

#161 [FEAT] 영화 정보 응답에 mainEmotion 속성 추가
  src/main/java/com/insidemovie/backend/api/movie/controller/MovieController.java
  src/main/java/com/insidemovie/backend/api/movie/dto/MovieSearchResDto.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java
Labels: FEAT

#163 [FEAT] 사용자 정보 조회 리뷰 개수(본 영화 개수) 추가
  src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java
  src/main/java/com/insidemovie/backend/api/member/dto/MemberInfoDto.java
  src/main/java/com/insidemovie/backend/api/member/service/MemberService.java
Labels: FEAT, CHORE

#150 [REFAC] 감정 상태 neutral -> disgust로 변경 및 데이터 마이그레이션 작업 수행
  build.gradle
  src/main/java/com/insidemovie/backend/api/constant/EmotionType.java
  src/main/java/com/insidemovie/backend/api/member/dto/emotion/EmotionAvgDTO.java
  src/main/java/com/insidemovie/backend/api/member/dto/emotion/MemberEmotionSummaryRequestDTO.java
  src/main/java/com/insidemovie/backend/api/member/dto/emotion/MemberEmotionSummaryResponseDTO.java
  src/main/java/com/insidemovie/backend/api/member/entity/MemberEmotionSummary.java
  src/main/java/com/insidemovie/backend/api/member/service/MemberService.java
  src/main/java/com/insidemovie/backend/api/movie/dto/emotion/MovieEmotionSummaryResponseDTO.java
  src/main/java/com/insidemovie/backend/api/movie/entity/MovieEmotionSummary.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java
  src/main/java/com/insidemovie/backend/api/recommend/dto/EmotionRequestDTO.java
  src/main/java/com/insidemovie/backend/api/recommend/service/EmotionRecommendationService.java
  src/main/java/com/insidemovie/backend/api/review/dto/EmotionDTO.java
  src/main/java/com/insidemovie/backend/api/review/entity/Emotion.java
  src/main/java/com/insidemovie/backend/api/review/repository/EmotionRepository.java
  src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V2__rename_neutral_to_disgust.sql
Labels: REFAC, SETTING

#171 Revert "Merge pull request #150 from AutoeverInsideMovie/refac/#141"
  build.gradle
  src/main/java/com/insidemovie/backend/api/constant/EmotionType.java
  src/main/java/com/insidemovie/backend/api/member/dto/emotion/EmotionAvgDTO.java
  src/main/java/com/insidemovie/backend/api/member/dto/emotion/MemberEmotionSummaryRequestDTO.java
  src/main/java/com/insidemovie/backend/api/member/dto/emotion/MemberEmotionSummaryResponseDTO.java
  src/main/java/com/insidemovie/backend/api/member/entity/MemberEmotionSummary.java
  src/main/java/com/insidemovie/backend/api/member/service/MemberService.java
  src/main/java/com/insidemovie/backend/api/movie/dto/emotion/MovieEmotionSummaryResponseDTO.java
  src/main/java/com/insidemovie/backend/api/movie/entity/MovieEmotionSummary.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java
  src/main/java/com/insidemovie/backend/api/recommend/dto/EmotionRequestDTO.java
  src/main/java/com/insidemovie/backend/api/recommend/service/EmotionRecommendationService.java
  src/main/java/com/insidemovie/backend/api/review/dto/EmotionDTO.java
  src/main/java/com/insidemovie/backend/api/review/entity/Emotion.java
  src/main/java/com/insidemovie/backend/api/review/repository/EmotionRepository.java
  src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V2__rename_neutral_to_disgust.sql
Labels: FIX

#173 [FIX] 신고하면 리뷰에 반영 안 되는 오류 수정
  src/main/java/com/insidemovie/backend/api/report/controller/ReportController.java
  src/main/java/com/insidemovie/backend/api/report/service/ReportService.java
  src/main/java/com/insidemovie/backend/api/review/dto/ReviewResponseDTO.java
  src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
Labels: FIX

#178 [FIX] 맞춤 영화 SecurityConfig 엔드포인트 추가
  src/main/java/com/insidemovie/backend/api/review/controller/ReviewController.java
  src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
  src/main/java/com/insidemovie/backend/common/config/security/SecurityConfig.java
Labels: FIX

#181 [FEAT] 영화 상세보기 응답 데이터 추가
  src/main/java/com/insidemovie/backend/api/movie/dto/MovieDetailResDto.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieDetailService.java
Labels: FEAT

#186 [FIX] 리뷰 관련 API 응답 형식 수정
  src/main/java/com/insidemovie/backend/api/review/controller/ReviewController.java
  src/main/java/com/insidemovie/backend/api/review/dto/ReviewCreatedResponseDTO.java
  src/main/java/com/insidemovie/backend/api/review/dto/ReviewResponseDTO.java
  src/main/java/com/insidemovie/backend/api/review/repository/ReviewRepository.java
  src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
  src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
Labels: FEAT

#188 [FIX] ReviewService 중복 코드 제거 및 메서드 간소화
  src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
Labels: FIX

#192 [FIX] 박스오피스 에러 해결
  src/main/java/com/insidemovie/backend/api/movie/controller/BoxOfficeController.java
  src/main/java/com/insidemovie/backend/api/movie/entity/boxoffice/DailyBoxOfficeEntity.java
  src/main/java/com/insidemovie/backend/api/movie/entity/boxoffice/WeeklyBoxOfficeEntity.java
  src/main/java/com/insidemovie/backend/api/movie/repository/DailyBoxOfficeRepository.java
  src/main/java/com/insidemovie/backend/api/movie/repository/WeeklyBoxOfficeRepository.java
  src/main/java/com/insidemovie/backend/api/movie/service/BoxOfficeService.java
  src/main/resources/application.yml
Labels: FIX

#193 [FEAT] 리뷰 목록에 정렬 기능 추가
  src/main/java/com/insidemovie/backend/api/constant/ReviewSort.java
  src/main/java/com/insidemovie/backend/api/review/constant/ReviewSortType.java
  src/main/java/com/insidemovie/backend/api/review/controller/ReviewController.java
  src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
Labels: FEAT

#195 Feat/#194
  src/main/java/com/insidemovie/backend/api/admin/controller/AdminController.java
  src/main/java/com/insidemovie/backend/api/constant/EmotionType.java
  src/main/java/com/insidemovie/backend/api/member/dto/emotion/EmotionAvgDTO.java
  src/main/java/com/insidemovie/backend/api/member/dto/emotion/MemberEmotionSummaryRequestDTO.java
  src/main/java/com/insidemovie/backend/api/member/dto/emotion/MemberEmotionSummaryResponseDTO.java
  src/main/java/com/insidemovie/backend/api/member/entity/MemberEmotionSummary.java
  src/main/java/com/insidemovie/backend/api/member/service/MemberService.java
  src/main/java/com/insidemovie/backend/api/movie/dto/emotion/MovieEmotionSummaryResponseDTO.java
  src/main/java/com/insidemovie/backend/api/movie/entity/MovieEmotionSummary.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java
  src/main/java/com/insidemovie/backend/api/recommend/dto/EmotionRequestDTO.java
  src/main/java/com/insidemovie/backend/api/recommend/service/EmotionRecommendationService.java
  src/main/java/com/insidemovie/backend/api/report/service/ReportService.java
  src/main/java/com/insidemovie/backend/api/review/dto/EmotionDTO.java
  src/main/java/com/insidemovie/backend/api/review/entity/Emotion.java
  src/main/java/com/insidemovie/backend/api/review/repository/EmotionRepository.java
  src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
  src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
Labels: FEAT

#197 Refac/#196
  src/main/java/com/insidemovie/backend/api/movie/controller/BoxOfficeController.java
  src/main/java/com/insidemovie/backend/api/movie/dto/MovieDetailResDto.java
  src/main/java/com/insidemovie/backend/api/movie/service/BoxOfficeService.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieDetailService.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java
  src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
Labels: REFAC

#198 [FEAT] 정지된 사용자 리뷰 작성 및 신고 기능 제한
  src/main/java/com/insidemovie/backend/api/member/entity/Member.java
  src/main/java/com/insidemovie/backend/api/member/entity/MemberEmotionSummary.java
  src/main/java/com/insidemovie/backend/api/member/service/MemberService.java
  src/main/java/com/insidemovie/backend/api/report/controller/ReportController.java
  src/main/java/com/insidemovie/backend/api/review/controller/ReviewController.java
  src/main/java/com/insidemovie/backend/common/exception/ForbiddenException.java
  src/main/java/com/insidemovie/backend/common/exception/UnAuthorizedException.java
  src/main/java/com/insidemovie/backend/common/response/ErrorStatus.java
  src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
Labels: FEAT, FIX, CHORE

#202 [FIX] SecurityConfig 예외 추가
  src/main/java/com/insidemovie/backend/common/config/security/SecurityConfig.java
Labels: FIX

#204 Feat/#172 영화 대결 기능
  src/main/java/com/insidemovie/backend/api/constant/EmotionType.java
  src/main/java/com/insidemovie/backend/api/match/controller/MatchController.java
  src/main/java/com/insidemovie/backend/api/match/entity/Match.java
  src/main/java/com/insidemovie/backend/api/match/entity/MovieMatch.java
  src/main/java/com/insidemovie/backend/api/match/entity/Vote.java
  src/main/java/com/insidemovie/backend/api/match/repository/MatchRepository.java
  src/main/java/com/insidemovie/backend/api/match/repository/MovieMatchRepository.java
  src/main/java/com/insidemovie/backend/api/match/repository/VoteRepository.java
  src/main/java/com/insidemovie/backend/api/match/scheduler/MatchScheduler.java
  src/main/java/com/insidemovie/backend/api/match/service/MatchService.java
  src/main/java/com/insidemovie/backend/api/movie/controller/MovieController.java
  src/main/java/com/insidemovie/backend/api/movie/dto/MovieDetailSimpleResDto.java
  src/main/java/com/insidemovie/backend/api/movie/dto/emotion/MovieEmotionResDTO.java
  src/main/java/com/insidemovie/backend/api/movie/dto/emotion/MovieEmotionSummaryResponseDTO.java
  src/main/java/com/insidemovie/backend/api/movie/entity/Movie.java
  src/main/java/com/insidemovie/backend/api/movie/repository/MovieRepository.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java
  src/main/java/com/insidemovie/backend/common/exception/IllegalStateException.java
  src/main/java/com/insidemovie/backend/common/response/ErrorStatus.java
  src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
  src/main/resources/application.yml
Labels: FEAT

#212 [FIX] 영화 리뷰 목록에 내 리뷰가 보이도록 수정
  src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
Labels: FIX

#215 [FIX] 리뷰 DTO 영화 관람일 반환값 추가
  src/main/java/com/insidemovie/backend/api/review/dto/ReviewResponseDTO.java
  src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
Labels: FIX

#216 [FIX] 리뷰 작성 시 영화/사용자 감정 정보 업데이트 누락 수정
  src/main/java/com/insidemovie/backend/api/member/dto/emotion/EmotionAvgDTO.java
  src/main/java/com/insidemovie/backend/api/member/entity/MemberEmotionSummary.java
  src/main/java/com/insidemovie/backend/api/member/service/MemberService.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java
  src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
Labels: FIX

#220 [FIX] fetch 변경
  src/main/java/com/insidemovie/backend/api/match/entity/Match.java
  src/main/java/com/insidemovie/backend/api/member/entity/Member.java
  src/main/java/com/insidemovie/backend/api/movie/entity/Movie.java
  src/main/java/com/insidemovie/backend/api/movie/entity/MovieEmotionSummary.java
  src/main/java/com/insidemovie/backend/api/review/entity/Review.java
Labels: FIX

#223 [FEAT] 응답에 대표 감정 수치랑 사용자 프로필 반환 추가
  src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java
  src/main/java/com/insidemovie/backend/api/member/entity/Member.java
  src/main/java/com/insidemovie/backend/api/member/service/MemberService.java
  src/main/java/com/insidemovie/backend/api/movie/dto/MovieSearchResDto.java
  src/main/java/com/insidemovie/backend/api/movie/dto/MyMovieResponseDTO.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieLikeService.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java
  src/main/java/com/insidemovie/backend/api/review/dto/ReviewResponseDTO.java
Labels: FEAT

#218 [REFAC] 영화 추출 카테고리 확장 및 추출 페이지 확장
  src/main/java/com/insidemovie/backend/api/movie/entity/Movie.java
  src/main/java/com/insidemovie/backend/api/movie/scheduler/MovieUpdateScheduler.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieService.java
  src/main/resources/application.yml
Labels: REFAC

#226 [FIX] 박스오피스 데이터 movieId에 `null`을 응답하는 것을 수정
  src/main/java/com/insidemovie/backend/api/movie/dto/boxoffice/DailyBoxOfficeResponseDTO.java
  src/main/java/com/insidemovie/backend/api/movie/dto/boxoffice/WeeklyBoxOfficeResponseDTO.java
Labels: FIX

#229 [REFAC] 사용자의 감성 상태 업데이트 기능 수정
  src/main/java/com/insidemovie/backend/api/member/controller/MemberController.java
  src/main/java/com/insidemovie/backend/api/member/dto/emotion/MemberEmotionSummaryRequestDTO.java
  src/main/java/com/insidemovie/backend/api/member/dto/emotion/MemberEmotionSummaryResponseDTO.java
  src/main/java/com/insidemovie/backend/api/member/service/MemberService.java
Labels: REFAC

#234 [FIX] 박스오피스 응답 구조 개선
  src/main/java/com/insidemovie/backend/api/movie/dto/boxoffice/DailyBoxOfficeResponseDTO.java
  src/main/java/com/insidemovie/backend/api/movie/dto/boxoffice/WeeklyBoxOfficeResponseDTO.java
  src/main/java/com/insidemovie/backend/api/movie/repository/MovieEmotionSummaryRepository.java
  src/main/java/com/insidemovie/backend/api/movie/service/BoxOfficeService.java
Labels: FIX

#240 [FEAT] 이메일 로그인 시 ROLE 반환 추가
  src/main/java/com/insidemovie/backend/api/member/dto/MemberLoginResponseDto.java
  src/main/java/com/insidemovie/backend/api/member/service/MemberService.java
Labels: FEAT, CHORE

#241 [FEAT] 사용자가 좋아요한 영화 감정 상태 변경 시, 자동으로 사용자의 감정 상태 변경 기능 추가
  src/main/java/com/insidemovie/backend/api/member/repository/MemberEmotionSummaryRepository.java
  src/main/java/com/insidemovie/backend/api/member/repository/MemberLikeRepository.java
  src/main/java/com/insidemovie/backend/api/member/service/MemberEmotionSummaryService.java
  src/main/java/com/insidemovie/backend/api/movie/repository/MovieLikeRepository.java
  src/main/java/com/insidemovie/backend/api/movie/service/MovieEmotionSummaryService.java
  src/main/java/com/insidemovie/backend/api/review/repository/ReviewRepository.java
  src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
Labels: FEAT

#244 [FEAT] 리뷰 응답에 사용자 대표 감정(memberEmotion) 추가
  src/main/java/com/insidemovie/backend/api/member/repository/MemberEmotionSummaryRepository.java
  src/main/java/com/insidemovie/backend/api/review/dto/ReviewResponseDTO.java
  src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
Labels: FEAT

#249 [FIX] Review 엔티티 modify 삭제
  src/main/java/com/insidemovie/backend/api/review/entity/Review.java
  src/main/java/com/insidemovie/backend/api/review/service/ReviewService.java
Labels: FIX

#252 [FIX] 회원가입 시 감정 상태 중복 등록 오류 수정
  src/main/java/com/insidemovie/backend/api/member/entity/MemberEmotionSummary.java
  src/main/java/com/insidemovie/backend/api/member/service/MemberService.java
Labels: FIX

#254 [FEAT] 이메일 인증 기능
  build.gradle
  src/main/java/com/insidemovie/backend/api/Email/Service/EmailService.java
  src/main/java/com/insidemovie/backend/api/Email/controller/EmailController.java
  src/main/java/com/insidemovie/backend/common/config/security/SecurityConfig.java
  src/main/java/com/insidemovie/backend/common/response/SuccessStatus.java
  src/main/resources/application.yml
Labels: FEAT
